---
# Test the backups ran as expected

- name: Verify
  hosts: all
  vars:
    expected_backup_dirs:
      - /backupdest/awesome-config/
      - /backupdest/opt/other-data/
      - /backupdest/opt/multiple/slashes
      - /other-backupdest/opt/separate-dest
    expected_restored_files:
      - /opt/test-restore/file-1
      - /opt/test-restore/file-2
  tasks:
  - name: Find backup directories
    ansible.builtin.stat:
      path: "{{ item }}"
    register: stat_result
    loop: "{{ expected_backup_dirs }}"

  - name: Verify backup directories all exist
    ansible.builtin.assert:
      that: stat_result.results[index].stat.exists
      fail_msg: "File {{ item }} not found"
    loop: "{{ expected_backup_dirs }}"
    loop_control:
      index_var: index

  - name: (Re)make a restore location
    ansible.builtin.file:
      path: /opt/test-restore
      state: "{{ item }}"
      mode: 0700
    loop:
      - absent
      - directory

  - name: Attempt to restore backup
    ansible.builtin.command: "/usr/local/bin/duplicity file:///backupdest/awesome-config /opt/test-restore"
    args:
      creates: "{{ expected_restored_files }}"
    environment:
      PASSPHRASE: duplicity

  - name: Find restored files
    ansible.builtin.stat:
      path: "{{ item }}"
    register: stat_result
    loop: "{{ expected_restored_files }}"

  - name: Verify restored files all exist
    ansible.builtin.assert:
      that: stat_result.results[index].stat.exists
      fail_msg: "File {{ item }} not found"
    loop: "{{ expected_restored_files }}"
    loop_control:
      index_var: index